[package]
name = "lightbookinput-linux-server"
description = "Linux Fcitx5 输入法的 Rust Server"
version = "1.0.20261014"
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "lightbookinput-linux-server"
path = "src/main.rs"

[dependencies]
lightbookinput-core.workspace = true
lightbookinput-dictionary.workspace = true
lightbookinput-learning.workspace = true
lightbookinput-lm.workspace = true
lightbookinput-neural.workspace = true
lightbookinput-platform.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-appender.workspace = true
libc = "0.2.189"

[lints]
workspace = true
